### ISSUE TITLE
Roadmap for Multi-GPU cuda healpix fft

### ISSUE THREAD

**Issue by ASKabalan** [astro-informatics/s2fft#207]
Quick roadmap on the multi GPU healpix FFT

For the single GPU one

- [ ] Merge first PR https://github.com/astro-informatics/s2fft/pull/204 that uses CUFFT as backend for FFTs and does the spectral extensions and folding in cuda kernels
- [ ] Merge all kernels in one to have parallel ffts in one kernel
- [ ] Handle reality case with C2R transforms

For the multi GPU one

- [ ] Discuss load balancing
1.  There is not way to distribute a healpix array in a clean way .. distributing must not have conditions on local slice index otherwise it will not scale
2. Distributing probably requires having a seperate padding function, that transforms a healpix array into a padded one with the shape of the corresponding FTM
3. Padded healpix array remains padded at all times to make sure that it is always distributable
4. FLM are squares so they can be easily distributed but only in 1 dimension since the other is always (number of rings) is always odd
- [ ] Implement padding operator
